- index.html
add filfreire to list of fans. https://github.com/filfreire/
> Add filfreire to list of fans

- index.html
fix 404 error: change relative path to absolute
> fix gitter link

- index.html
>  Added some links and a fun.

- index.html
> Add Kactoos, Kotlin port of Cactoos

- index.html
> Add @maratori to fans

- index.html
> Add "cactoos-http" project.

- index.html
Add cactoos-json to libraries:
> Add cactoos-json library

- index.html
Added 2 of my articles, which I think best describe the advantages of EO-style + a few libraries and a project.
> Added more resources

- index.html
No public methods without @Override
> Priciple about @Override rewriten not in Java-way

- index.html
Hi @yegor256.
Let me introduce my new tool for managing puzzles - [@puzzlerbot](https://github.com/skapral/puzzlerbot). It is supposed to work either alone or in pair with [0pdd](https://github.com/yegor256/0pdd/). It's aim is to provide new ways of organizing PDD approach in GitHub.
Hope it would be helpful for our EO community.
> Introducing Puzzler-bot

- index.html
Renamed Vgv-xls library to excel-io
> Renamed Vgv-xls library

- index.html
Added my blog to the list of contributions.
> Added pragmaticobjects.com

- index.html
Let's add @fabriciofx as a fan.
> Add @fabriciofx as a fan

- index.html
Let's add [cactoos-jdbc](https://github.com/fabriciofx/cactoos-jdbc) to framework/libraries list.
> Add cactoos-jdbc

- index.html
Let's add cactoos-matchers to frameworks/libraries list.
> Add cactoos-matchers

- index.html
We currently rewrite a rather complex project of ours. We started from scratch and with EO principles and work with them for over a year now.
In search of solutions for a whole app, we studied Zerocracy and kind of extracted a storage layer which enables us to build our entities in the form of „xml speaking objects“ from it.
We made it threadsafe, cacheable and added some flexibility so that it suits our needs.
Its open source, we would like to present it on your page.
> Add Xive, a EO conform data storage layer

- index.html
Added link to [verano-http](https://github.com/Vatavuk/verano-http) EO style http client.
> Verano-http EO library added

- index.html
> pragmaticobjects.com added

- index.html
Adding myself, my blog and my open source libs.
> Added vzurauskas

- index.html
We ported the verano-http library to C#.
> Add yaapii.http - C# port of verano-http

- index.html
Add https://github.com/elegant-bro to the libraries list
> Add elegant-bro repository

- index.html
> Add @pinguinjkeke to the list of fans

- index.html
I love this approach and principles of Elegant Objects. I'm pleased to be part of fans list. :)
> Add myself to fans list

- index.html
Hi @yegor256, I recently read a lot of your posts and I’m kinda motivated to write my own one. The following post talks about “NO for temporal coupling design” and since I come from Android dev background, the post is a bit Android n Kotlin-ish. So I think it’ll be nice and cool if this OOP-related post could be highlighted on this EO site, though I’m not sure if it deserves enough :)
https://proandroiddev.com/stop-crafting-your-time-bomb-39f2d26987e0
Also, I add my name to the fan section. Kindly for your review. Thanks!
> Add temporal coupling post & my name to fan section

- index.html
Added [rocket-3](https://github.com/rocket-3) to the fan list
> Add myself as a fan

- index.html
Added [Self XDSD](https://self-xdsd.com) as EO Product
> Added Self XDSD as EO Product

- index.html
Update index.html Added @ratra1 in fans
> Update index.html Added @ratra1 in fans

- index.html
Hi Yegor.
It used to be fun and inspiring being a part of EO community back in the times, but it's time for me to leave.
I never had a habit to intentionally cancel people in Internet or forcing my opinion to anyone. That helped me all these times to stay neutral towards your new hobby, which I have always found totally disgraceful: collecting nasty speculations in "Sozidanie", and provoking political hatred in Twitter. Still, since you've found this new hobby, I feel that EO became dead and abandoned. And in scope of the current madness in Ukraine going on, I don't want to stay neutral anymore. This is too much for me.
PS: I'd be appreciate if you remove my speech from the first Objects Meetup (about DI containers) from Youtube.
> Unfortunately, it's time for me to leave

- index.html
Added [reikai](https://github.com/kerelape/reikai) and removed [memoria](https://github.com/kerelape/memoria) because its functionality is implemented in the new library
> Add reikai

- index.html
> New fan added

- index.html
@yegor256 Please, add me to the fan list
> added to the fan list

- index.html
> elegram api by l3r8yJ

- index.html
I consider myself a fan of EO and I want to put my name on the site.
> docs: add fan birdflu

- index.html
some unnecessary spaces are removed automatically, but I can get them back
> add me to fans

- index.html
Hi, I'm inspired by your approach to writing code
> add @Empiree to fans

- index.html
Organized <a> tags with indentation based on the starting letter for improved readability
> add fan @gennadygennady

- index.html
In this PR I add @ivanovmg into the list of Elegant Object fans.
Thank you!
> Add fan @ivanovmg

- index.html
> add fan @Karpikova

- index.html
Hi, @yegor256! 
I want to say a big thank you for your book — it completely changed the way how I see object-oriented programming.
It made me think differently about code design, and it even made me professionally unfit in some way)
Thanks for contribution and sharing your knowledge!
> Added fan of Elegant Objects book.
